# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Test Build

on:
  push:
  workflow_dispatch:

jobs:
  maven_build:
    name: Maven-Build (Linux)
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      activemq:
        image: quay.io/artemiscloud/activemq-artemis-broker:latest
        ports:
          - 61616:61616
        env:
          AMQ_USER: admin
          AMQ_PASSWORD: admin

      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: postgres

      minio:
        image: lazybit/minio
        ports:
          - 8100:9000
          - 8101:9001
        env:
          MINIO_ROOT_USER: minioadmin      # Admin Access Key
          MINIO_ROOT_PASSWORD: minioadmin
        volumes:
          - ${{ github.workspace }}/data:/data
        options: --name=minio --health-cmd "curl http://localhost:9000/minio/health/live"
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: sonarqube update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -Dsonar.token=${{ secrets.SONAR_TOKEN }} sonar:sonar